#!/usr/bin/env bash
#Bash script that displays To infinity and beyond indefinitely.

#Requirements:
#Add a sleep 2 in between each iteration

while true; do
		echo "To infinity and beyond"
		sleep 2
done
