#!/usr/bin/env bash
# Uses a while loop to display Best School 10 times, and Hi on new line for the 9th iteration
i="0"
while [ $i -lt 10 ]; do
	echo "Best School"
	if [ $i -eq 8 ]
	then
		echo "Hi"
	fi
	(( i++ ))
done
